os: windows
language: shell

env:
  global:
    - GOVERSION: 1.12.4
    - JAVA_HOME: /c/opt/jdk
    - ANT_HOME: /c/opt/ant
    - GOPATH: /c/opt/gopath
    - GOROOT: /c/opt/go

before_install:
  - export PATH=${JAVA_HOME}/bin:${ANT_HOME}/bin:${GOPATH}/bin:${GOPATH}/bin/windows_386:${GOROOT}/bin:${PATH}
  - mkdir -p /c/opt
  - set

install:
  - |
    curl -fsS -o openjdk.zip https://download.oracle.com/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip
    7z x openjdk.zip -y -o/c/opt/
    mv /c/opt/jdk-11.0.2 ${JAVA_HOME}
    java -version
    rm -f openjdk.zip
  - |
    curl -fsS -o apache-ant.zip http://mirrors.standaloneinstaller.com/apache//ant/binaries/apache-ant-1.10.5-bin.zip
    7z x apache-ant.zip -y -o/c/opt/
    mv /c/opt/apache-ant-1.10.5 ${ANT_HOME}
    ant -version
    rm -f apache-ant.zip
  - |
    curl -fsS -o go.zip https://storage.googleapis.com/golang/go${GOVERSION}.windows-amd64.zip
    7z x go.zip -y -o/c/opt/
    go version
    go env
    rm -f go.zip

script:
  - ant release

deploy:
  provider: releases
  api_key:
    secure: GDkgrNa2WuYTLkqfyr4mi2+qTNO4ea+ffJhlTsO3PEZZFLAkSo+Lr95lGQ2RAeZPm+XvsQBLhyJZTnfsJUBG3Rp7qNwIVjo+oQMNEQvHDdG0GkljN3Smtr4Ldi8rcHy3atlI62/h2w4FHodrdswBnp787ksCHzdWCQ3YpOj/PtDmD2dAsxqNrQZIWeLJ9boTKTxeZygi7Ru+DauwbO1fC1qL57hQ/hvubUfobqbzTppxza+gTbxtw1p5uUGhWx3Xx21z1lkVLIT4oShaj63J6fCRVhWi0G3Mq41yzqJ2PqCSQum5wFhx07FFU+703Fu2gg2jxLElBsvLx9PBwu1iS5hdCheuQ/wHE3aOuTEW/9QRII66hs6WkRz6rH9jScUezHdYP1Ky0x+dp/ngSGDegWf9rSoj+3R46DTBxOtFaELmDiBAbYOyXXemuLqTFbVMuXbdRlS0hIBsMcH3Ow4VlVh4OSm272r/VBz7tzl/25kMAZmNQpus6nOUaRFGTEO9pmsRjw61JStZxEp1X12oz/i0ZFSW9yBEhvL0UX6CH1AEPpJ/bd6MlSkH8JQoLyOjELhPPfQi5A8Ta/N4VVpLEFkhKTmNeWmsO8f4yE0Y0thsLM8lA2hOk3u87Fs/YcnFN53Bv17YQYocBFIQqxHoZbHbiULxJvYZCEy82nwMVSU=
  file_glob: true
  file: bin/release/*
  skip_cleanup: true
  draft: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
