[metadata]
package = "github.com/crazy-max/WindowsSpyBlocker"
homepage = "https://github.com/crazy-max/WindowsSpyBlocker"
license = "MIT"

[[constraint]]
  name = "github.com/0xrawsec/golang-evtx"
  revision = "bd7e3686e12fa8f16624801208fe70e5e9a90fc7"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/cavaliercoder/grab"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/cevaris/ordered_map"
  revision = "531fd444821a2eda0e8d1ed033ae207641e03b54"

[[constraint]]
  name = "github.com/fatih/color"
  version = "~1.4.1"

[[constraint]]
  name = "github.com/go-ole/go-ole"
  revision = "de8695c8edbf8236f30d6e1376e20b198a028d42"

[[constraint]]
  name = "github.com/hako/durafmt"
  revision = "83a6d8dc879e5db09185e352561da4326f443de6"

[[constraint]]
  name = "github.com/mcuadros/go-version"
  revision = "257f7b9a7d87427c8d7f89469a5958d57f8abd7c"

[[constraint]]
  name = "github.com/miekg/dns"
  revision = "e78414ef75607394ad7d917824f07f381df2eafa"

[[constraint]]
  name = "golang.org/x/sys"
